# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

variables:
- group: "anchore"
- group: "dockerhub"
- name: APPLICATION
  value: anchorectl-test
- name: VERSION
  value: HEAD
- name: GITHUB_SERVER_URL
  value: github.com
- name: REPOSITORY
  value: pvnovarese/anchorectl-test


pool:
  vmImage: ubuntu-latest


steps:
- checkout: self
  displayName: Checkout

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- script: |
    curl -sSfL https://anchorectl-releases.anchore.io/anchorectl/install.sh | sh -s -- -b ${HOME}/.local/bin v1.7.0
    curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b ${HOME}/.local/bin v0.80.0
    curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b ${HOME}/.local/bin
    export PATH="${HOME}/.local/bin/:${PATH}"
  displayName: 'Install anchorectl Binary'

- script: |
    anchorectl version
    anchorectl system status
    anchorectl feed list
    env
  displayName: 'Connectivity Check'

- script: |
    syft -o json . | anchorectl source add --wait ${GITHUB_SERVER_URL}/${REPOSITORY}@${sourceVersion:0:7} --application ${APPLICATION}@${VERSION} --from -
    syft -o json . | grype
    anchorectl source vulnerabilities ${GITHUB_SERVER_URL}/${REPOSITORY}@${sourceVersion:0:7}
  env: { sourceVersion: $(Build.SourceVersion) }
  displayName: 'Generate SBOM and Pull Vulns'

